name: License Scanning

on:
  - pull_request
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run FOSSA scan and upload build result
        uses: fossa-contrib/fossa-action@warn-message
        with:
          fossa-api-key: ${{ secrets.FOSSA_API_KEY }}
